---
name: "Aptly deb repo creator"
author: "Jinna Kiisuo <jinnak@nocturnal.fi>"
description: |
  Create ad-hoc deb repositories into GitHub artifacts.
  These can be published onwards into GitHub Pages.

inputs:
  name:
    description: |
      "Short name of the project used as a slug to refer to your repo."
    required: true
  prefix:
    description: |
      Repo prefix in the published structure.
      Relevant if publishing to multiple distros as they can't mix.
    required: true
    default: "."
  repos:
    description: |
      "Repositories to create. Provided as a semicolon separated csv."
    required: true
    default: "debian;stable;amd64;./*.deb"
  gpg_key_id:
    description: |
      ID of the GPG public key to use for signing.
      Useful for definining a signing specific subkey.
    required: true
    default: ""
  gpg_private_key:
    description: Armored gpg private key to sign the repo with.
    required: true
  gpg_passphrase:
    description: The passphrase of the provided GPG key.
    required: true

  GITHUB_TOKEN:
    description: |
      A GitHub token, available in the secrets.GITHUB_TOKEN working-directory variable.
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Fix up PATH
      shell: bash
      run: |
          mkdir "${HOME}/bin"
          echo "${HOME}/bin" >> $GITHUB_PATH
          echo "${{ github.action_path }}" >> $GITHUB_PATH
    - name: Install Aptly
      uses: myci-actions/add-deb-repo@11
      with:
        # TODO: Swap out ci prefix for release once Aptly 1.6.0 is published:
        # https://github.com/aptly-dev/aptly/discussions/1345
        repo: deb http://repo.aptly.info/ci noble main
        repo-name: aptly
        keys-asc: http://repo.aptly.info/pubkey.txt
        install: aptly
    - name: Install UBI
      shell: bash
      run: |
        curl --silent --location \
            https://raw.githubusercontent.com/houseabsolute/ubi/master/bootstrap/bootstrap-ubi.sh |
            sh
    - name: Install XSV
      shell: bash
      run: ubi -p BurntSushi/xsv -i "$HOME/bin/"
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: "${{ inputs.gpg_private_key }}"
        passphrase: "${{ inputs.gpg_passphrase }}"
    - name: Create repository
      shell: bash
      run: |
        echo "${{ inputs.repos }}" | create-aptly-repos.sh "${{ inputs.name }}" "${{ inputs.prefix }}"
    - name: Admire results
      shell: bash
      run: |
        tree "$HOME/.aptly/public"
