---
name: "Aptly deb repo creator"
author: "Jinna Kiisuo <jinnak@nocturnal.fi>"
branding:
  color: red
  icon: aperture
description: |
  Create APT compatible debian repositories into GitHub artifacts with Aptly.

inputs:
  name:
    description: |
      "Short name of the project used as a slug to refer to your repo."
    required: true
  prefix:
    description: |
      Repo prefix in the published structure.
      Relevant if you wish to separate say ubuntu & debian completely.
    required: true
    default: "."
  repos:
    description: |
      Repository definitions to create. Provided as a comma separated csv.
      The architecture list should be quoted and comma separated.
      Fields are in order: distribution, category, architectures, filesystem glob of debs.
      The default thus creates a single distribution of "bookworm", category "stable" for amd64 of all debs in the current directory.
    required: true
    default: bookworm,stable,\"amd64\",./*.deb
  gpg_key_id:
    description: |
      ID of the GPG public key to use for signing.
      Useful for definining a signing specific subkey.
      Defaults to whatever GnuPG defaults to.
    required: false
    default: ""
  gpg_private_key:
    description: Armored gpg private key to sign the repo with.
    required: true
  gpg_passphrase:
    description: The passphrase of the provided GPG key.
    required: true

  GITHUB_TOKEN:
    description: |
      A GitHub token, available in the secrets.GITHUB_TOKEN working-directory variable.
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Fix up PATH
      shell: bash
      run: |
          mkdir "${HOME}/bin"
          echo "${HOME}/bin" >> $GITHUB_PATH
          echo "${{ github.action_path }}" >> $GITHUB_PATH
    - name: Install Aptly
      uses: myci-actions/add-deb-repo@11
      with:
        # TODO: Swap out ci prefix for release once Aptly 1.6.0 is published:
        # https://github.com/aptly-dev/aptly/discussions/1345
        repo: deb http://repo.aptly.info/ci noble main
        repo-name: aptly
        keys-asc: http://repo.aptly.info/pubkey.txt
        install: aptly
    - name: Install UBI
      shell: bash
      run: |
        curl --silent --location \
            https://raw.githubusercontent.com/houseabsolute/ubi/master/bootstrap/bootstrap-ubi.sh |
            sh
    - name: Install XSV
      shell: bash
      run: ubi -p BurntSushi/xsv -i "$HOME/bin/"
    - name: Import GPG key
      id: gpg_import
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: "${{ inputs.gpg_private_key }}"
        passphrase: "${{ inputs.gpg_passphrase }}"
        fingerprint: "${{ inputs.gpg_key_id }}"
    - name: Create repository
      shell: bash
      run: |
        echo "${{ inputs.repos }}" | create-aptly-repos.sh "${{ inputs.name }}" "${{ inputs.prefix }}"
    - name: Export public key
      shell: bash
      run: gpg --export --armor "${{ steps.gpg_import.outputs.fingerprint }}" > ~/.aptly/public/GPG.key
    - name: Print repo tree
      shell: bash
      run: |
        tree "$HOME/.aptly/public"
    - name: Publish artifact
      uses: actions/upload-artifact@v4
      with:
        name: "${{ inputs.name }}-${{inputs.prefix}}-repo-artifacts"
        path: ~/.aptly/public
        if-no-files-found: error
